# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

variables:
  vmImageName: ubuntu-latest

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ragc-vuepoc-acr'
        repository: 'vuepoc/hello-world-vue/custom'
        command: 'buildAndPush'
        Dockerfile: 'hello-world/Dockerfile'
        buildContext: 'hello-world'
        tags: $(Build.BuildId)
        addPipelineData: true

- stage: DeployAppSvcLinux
  displayName: Deploy Custom Container
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'AppSvcLinux-VueJs-Custom'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'FTA Subscription'
              appName: 'ragc-appsvc-linux-vuejs-custom'
              containers: 'ragcvuepoc.azurecr.io/vuepoc/hello-world-vue/custom:$(Build.BuildId)'


