# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

variables:
  vmImageName: ubuntu-latest

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Docker@2
      displayName: Blessed Build
      inputs:
        containerRegistry: 'ragc-vuepoc-acr'
        repository: 'netcore/hello-world-net5/blessed'
        command: 'buildAndPush'
        Dockerfile: 'hello-world-net5/Blessed.Dockerfile'
        buildContext: 'hello-world-net5'
        tags: $(Build.BuildId)
        addPipelineData: true

- stage: DeployLinuxContainerBlessedBuild
  displayName: Deploy Blessed Build Container
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'AppSvcLinux-Net5-Blessed'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'FTA Subscription'
              appName: 'test-deployment-center-linux'
              containers: 'ragcvuepoc.azurecr.io/netcore/hello-world-net5/blessed:$(Build.BuildId)'
          # - task: AzureAppServiceSettings@1
          #   inputs:
          #     azureSubscription: 'FTA Subscription'
          #     appName: 'test-deployment-center-linux'
          #     resourceGroupName: ragc-appsvc-linux-rsg
          #     appSettings:  |
          #       [
          #         {
          #           "name": "CONTAINER_CONFIGURED",
          #           "value": "ragcvuepoc.azurecr.io/netcore/hello-world-net5/blessed:$(Build.BuildId)",
          #           "slotSetting": false
          #         }
          #       ]

