# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - test-dcenter-2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ragcvuepoc.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4dc3ef044f6e49c2a371345f50d137f7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ba3d5a8ec836461b95e917ae227b5d76 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_4dc3ef044f6e49c2a371345f50d137f7 }}/netcore/hello-world-net5/blessed:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test-dcenter-2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_62bfe08450d64d14ae6eef10e3195e4b }}
        images: 'ragcvuepoc.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4dc3ef044f6e49c2a371345f50d137f7 }}/netcore/hello-world-net5/blessed:${{ github.sha }}'